name: Deploy Personal Dashboard

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: |
          npm run lint

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.APP_NAME }} .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Tag and Push Docker image
        run: |
          docker tag ${{ vars.APP_NAME }} ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.APP_NAME }}:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.APP_NAME }}:latest

      - name: Cleanup Docker
        run: |
          docker rmi $(docker images -f "dangling=true" -q) || true
          docker system prune -af

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    environment:
      name: Production
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.APP_NAME }}:latest
            docker stop ${{ vars.APP_NAME }} || true
            docker rm ${{ vars.APP_NAME }} || true
            docker rmi $(docker images -f "dangling=true" -q) || true
            docker system prune -af
            docker run -d --restart unless-stopped --name ${{ vars.APP_NAME }} -p 3000:3000 ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.APP_NAME }}:latest
